api/urls.py
from django.urls import path

from api.views.attaching_to_block_api_view import AttachingToBlockSimpleView, AttachingToBlockApiView
from api.views.events_api_view import EventsSimpleView, EventApiView
from api.views.like_api_view import UserLikeView
from accounts.views.auth import CheckAuthView
from api.views.list_votes import ListVotesSimpleView, ListVotesApiView
from api.views.name_voting_types_api_view import NameVotingTypesSSimpleView, NameVotingTypesSApiView
from api.views.news_api_view import NewsSimpleView, NewsApiView
from api.views.profile import AccountsSimpleView, AccountApiView
from api.views.reviews_api_view import ReviewsSimpleView, ReviewApiView
from api.views.newsline import NewslineApiView
from api.views.users_who_voted_api_view import UsersWhoVotedSimpleView, UsersWhoVotedApiView
from api.views.vote_api_view import VoteApiView, VoteSimpleView
from api.views.voting_options import VotingOptionsSimpleView, VotingOptionsApiView
from api.views.voting_types_api_view import VotingTypesSimpleView, VotingTypesApiView

urlpatterns = [
    path('events/', EventsSimpleView.as_view(), name="events_list"),
    path('events/<int:pk>', EventApiView.as_view(), name="events"),
    path('news/', NewsSimpleView.as_view(), name="news_list"),
    path('news/<int:pk>', NewsApiView.as_view(), name="news"),
    path('vote/', VoteSimpleView.as_view(), name="vote_list"),
    path('vote/<int:pk>', VoteApiView.as_view(), name="vote"),
    path('name_voting_types/', NameVotingTypesSSimpleView.as_view(), name="name_voting_types_list"),
    path('name_voting_types/<int:pk>', NameVotingTypesSApiView.as_view(), name="name_voting_types"),
    path('voting_types/', VotingTypesSimpleView.as_view(), name="voting_types_list"),
    path('voting_types/<int:pk>', VotingTypesApiView.as_view(), name="voting_types"),
    path('voting_options/', VotingOptionsSimpleView.as_view(), name="voting_options_list"),
    path('voting_options/<int:pk>', VotingOptionsApiView.as_view(), name="voting_options"),
    path('users_who_voted/', UsersWhoVotedSimpleView.as_view(), name="users_who_voted_list"),
    path('users_who_voted/<int:pk>', UsersWhoVotedApiView.as_view(), name="users_who_voted"),
    path('list_of_votes/', ListVotesSimpleView.as_view(), name="list_of_votes_list"),
    path('list_of_votes/<int:pk>', ListVotesApiView.as_view(), name="list_of_votes"),
    path('attaching_to_block/', AttachingToBlockSimpleView.as_view(), name="attaching_to_block_list"),
    path('attaching_to_block/<int:pk>', AttachingToBlockApiView.as_view(), name="attaching_to_block"),
    path("reviews/", ReviewsSimpleView.as_view(), name="reviews_list_api"),
    path("reviews/<int:pk>", ReviewApiView.as_view(), name="reviews_api"),
    path("newsline/", NewslineApiView.as_view(), name="newsline_api"),
    path("accounts/", AccountsSimpleView.as_view(), name="accounts_list"),
    path('accounts/<int:pk>', AccountApiView.as_view(), name="events"),
    path('user_like/<int:id>', UserLikeView.as_view(), name='user_like'),
    path('check_auth/', CheckAuthView.as_view(), name='check_auth'),
]

app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView


urlpatterns = [
    path("admin/", admin.site.urls),
    # path('__debug__/', include('debug_toolbar.urls')),
    path('auth/', include('accounts.urls')),
    path("", include('webapp.urls')),
    path("chat/", include('chat.urls')),
    path('api/', include('api.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('', include('cal.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
import uuid
from django.db import models
from django.utils import timezone
from enum import Enum
import logging

from accounts.models import Account

logger = logging.getLogger(__name__)


class ChatType(Enum):
    PRIVATE = "Private"
    GROUP = "Group"


class ChatRoom(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    chat_type = models.CharField(
        max_length=7,
        choices=[(tag.name, tag.value) for tag in ChatType],
        default=ChatType.PRIVATE,
    )
    users = models.ManyToManyField(Account, through='ChatRoomMembership', related_name='chat_rooms')
    avatar = models.ImageField(upload_to='groupchats/', null=True, blank=True)
    creator = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='created_groups',
                                null=True, blank=True)

    def is_group_chat(self):
        return self.chat_type == ChatType.GROUP.name

    def get_user_list(self):
        return [user.username for user in self.users.all()]


class ChatRoomMembership(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    chat_room = models.ForeignKey(ChatRoom, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        logger.debug(f"ChatRoomMembership created: User - {self.user.username}, Room - {self.chat_room.name}")


class File(models.Model):
    file = models.FileField(upload_to='chatfiles/')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    room = models.ForeignKey(ChatRoom, on_delete=models.CASCADE, related_name='files')
    chat_message = models.ForeignKey('ChatMessage', on_delete=models.CASCADE, null=True, blank=True,
                                     related_name='related_files')


class ChatMessage(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    room = models.ForeignKey(ChatRoom, on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(default=timezone.now)
    file = models.ForeignKey(File, on_delete=models.SET_NULL, null=True, blank=True)
    file_url = models.URLField(null=True, blank=True)

    def display_timestamp(self):
        return self.timestamp.strftime("%Y-%m-%d %H:%M:%S")

    class Meta:
        ordering = ['timestamp']

events_app/models/events.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator


class Events(models.Model):
    name = models.CharField(
        max_length=200,
        null=False,
        blank=False,
        verbose_name="Наименование"
    )
    cities = models.ForeignKey(
        to='support_app.Cities',
        related_name='сities',
        on_delete=models.CASCADE,
        verbose_name="Город",
        null=True,
        blank=True
    )
    type_events = models.ForeignKey(
        to='events_app.TypeEvents',
        related_name='type_events',
        on_delete=models.CASCADE,
        verbose_name="Тип мероприятия",
        null=False,
        blank=False
    )
    events_at = models.DateTimeField(
        verbose_name="Дата мероприятия",
        null=False,
        blank=False
    )
    sponsor = models.ForeignKey(
        to=get_user_model(),
        related_name='sponsor',
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        verbose_name='Организатор'
    )
    number_of_seats = models.IntegerField(
        null=False,
        blank=False,
        validators=[MinValueValidator(2), MaxValueValidator(100)],
        verbose_name="Количество мест"
    )
    start_register_at = models.DateTimeField(
        verbose_name="Дата начала регистрации",
        null=True,
        default=None
    )
    end_register_at = models.DateTimeField(
        verbose_name="Дата конца регистрации",
        null=True,
        blank=True
    )
    resident_booked = models.ManyToManyField(
        to=get_user_model(),
        through='UserBooked',
        related_name='user_booked',
        blank=True,
        verbose_name='Бранированные резиденты'
    )
    description = models.TextField(
        max_length=3000,
        null=False,
        verbose_name="Описание"
    )
    place = models.CharField(
        max_length=200,
        null=True,
        verbose_name="Место"
    )
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0,
        verbose_name="Цена"
    )
    is_deleted = models.BooleanField(
        verbose_name="Удалено",
        null=False,
        default=False
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата добавления"
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name="Дата обнавления"
    )
    photo = models.ForeignKey(
        to='support_app.Image',
        related_name='event_image',
        on_delete=models.CASCADE,
        verbose_name="Фото мероприятия",
        null=True,
        blank=True,
    )

    def delete(self, using=None, keep_parents=False):
        self.is_deleted = True
        self.deleted_at = timezone.now()
        self.save()

    def __str__(self):
        return f"Event {self.name} - started {self.events_at}"


class UserBooked(models.Model):
    resident = models.ForeignKey(
        to=get_user_model(),
        null=False,
        blank=False,
        on_delete=models.CASCADE,
        verbose_name='Забронировал'
    )
    event = models.ForeignKey(
        to=Events,
        null=False,
        blank=False,
        on_delete=models.CASCADE,
        verbose_name='Мероприятие'
    )
    booking_date = models.DateTimeField(
        null=False,
        blank=False
    )
    date_of_payment = models.DateTimeField(
        null=True,
        blank=True
    )
    cancellation_date = models.DateTimeField(
        null=True,
        blank=True
    )

    def __str__(self):
        return f"resident id-{self.resident} booking in events_app id-{self.event}"

api/views/newsline.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from api.serializers import EventsSerializer, NewsSerializer
from webapp.models import Events, News
from rest_framework.permissions import IsAuthenticated

class NewslineApiView(APIView):
    permission_classes = (IsAuthenticated,)

    def get(self, request, *args, **kwargs):
        events = Events.objects.all().order_by('created_at')
        news = News.objects.all().order_by('created_at')
        all_news = []
        serializer_news = NewsSerializer(news, many=True).data
        serializer_events = EventsSerializer(events, many=True).data
        for event in serializer_events:
            all_news.append(event)
        for news_alone in serializer_news:
            all_news.append(news_alone)
        for i in range(len(all_news)):
            for j in range(len(all_news)):
                if all_news[i]["created_at"] > all_news[j]["created_at"]:
                    all_news[i], all_news[j] = all_news[j], all_news[i]
        return Response(all_news, status=status.HTTP_200_OK)

events_app/views/newsline.py
from django.views.generic import TemplateView
from events_app.models import Events, News


class NewslineView(TemplateView):
    template_name = 'newsline.html'

webapp/views/events.py
from django.shortcuts import redirect
from django.views.generic import DetailView, CreateView, UpdateView

from webapp.forms import EventsForm
from webapp.models import Events


class EventDetailView(DetailView):
    model = Events
    template_name = 'event_detail.html'
    context_object_name = 'event'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        total_seats = self.object.number_of_seats
        booked_seats = self.object.resident_booked.count()
        available_seats = total_seats - booked_seats
        context['available_seats'] = available_seats
        return context


class EventsCreateView(CreateView):
    template_name = 'create_events.html'
    model = Events
    form_class = EventsForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            gallery = form.save(commit=False)
            gallery.author = self.request.user
            form.save()
            return redirect('/newsline')
        context = {'form': form}
        return self.render_to_response(context)


class EventsUpdateView(UpdateView):
    template_name = 'events_update.html'
    model = Events
    form_class = EventsForm
    success_url = '/newsline'

webapp/views/newsline.py
from django.views.generic import ListView
from django.http import HttpResponseRedirect
from django.urls import reverse
from rest_framework.permissions import IsAuthenticated
from accounts.cookie_auth import CookieJWTAuthentication
from rest_framework.exceptions import AuthenticationFailed

from webapp.models import Events


class NewslineView(ListView):
    model = Events
    template_name = 'newsline.html'
    context_object_name = 'events'
    authentication_classes = [CookieJWTAuthentication]
    permission_classes = [IsAuthenticated]

    def dispatch(self, request, *args, **kwargs):
        authenticator = self.authentication_classes[0]()
        try:
            user_auth_tuple = authenticator.authenticate(request)
        except AuthenticationFailed:
            return HttpResponseRedirect(reverse('login'))
        else:
            if user_auth_tuple:
                request.user, request.auth = user_auth_tuple
            else:
                return HttpResponseRedirect(reverse('login'))
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['events'] = Events.objects.all().exclude(is_deleted=True).order_by('-created_at')
        context['user_obj'] = self.request.user
        return context

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,500;1,500&display=swap"
          rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="base_styles">
    <div class="header">
        <div class="container">
            <div class="titany_logo">
                <img src="{% static 'svg/titany_logo.png' %}" alt="LOGO" class="titany_logo_img">
            </div>
            {% block header %}
            {% endblock %}
            <div class="burger_menu_custom_div">
                <nav class="burger_menu_nav_custom">
                    <div class="burger-button">
                        <span class="burger-top"></span>
                        <span class="burger-middle"></span>
                        <span class="burger-bottom"></span>
                    </div>
                    <div class="burger-menu">
                        <div class="navi_admin">
                            <a href="">Администратор</a>
                        </div>
                        <a href="" class="exit_but" onclick="event.preventDefault(); logout();">Выйти</a>
                    </div>
                </nav>
            </div>
        </div>
    </div>
    <nav class="navbar">
        <div class="container">
            <div class="nav_menu">
                <ul class="menu">
                    <li class="svg">
                        <a class="svg_link" href="{% url 'newsline' %}">
                            <img style="width: 41px; height: 41px" src="{% static 'svg/newsline.png' %}" alt="Новости"/>
                        </a>
                    </li>
                    <li class="svg">
                        <a class="svg_link" href="{% url 'chat_list' %}">
                            <img style="width: 41px; height: 41px" src="{% static 'svg/chat.png' %}" alt="Чаты"/>
                        </a>
                    </li>
                    <li class="svg">
                        <a class="svg_link" href="{% url 'calendar' %}">
                            <img style="width: 41px; height: 41px" src="{% static 'svg/events.png' %}"
                                 alt="Мероприятия"/>
                        </a>
                    </li>
                    <li class="svg">
                        <a class="svg_link" href="{% url 'account_list' %}">
                            <img style="width: 41px; height: 41px" src="{% static 'svg/profile.png' %}"
                                 alt="Резиденты"/>
                        </a>
                    </li>
                </ul>
            </div>

        </div>
    </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <div class="bottom_indent"></div>
    {% block script_block %}
        <script src="{% static 'js/logout.js' %}"></script>
        <script src="{% static 'js/check_auth.js' %}"></script>
        <script src="{% static 'js/calendar_script.js' %}"></script>
        <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js'></script>
        <script src="{% static 'js/burger.js' %}"></script>
    {% endblock %}
</div>

</body>
</html>

templates/base_calendar.html
{% extends "base.html" %}
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"
          integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Django Calendar App</title>
</head>
<body>
<h1 class="title">{% block title %}{% endblock %}</h1>
<hr>
{% block content %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
{% block script %}
{% endblock %}
</body>
</html>

templates/calendar.html
{% extends 'base_calendar.html' %}
{% load static %}

{% block title %}
    Calendar
{% endblock %}

{% block content %}
    <div class="calendar-container">
        <div class="calendar-wrapper">
            {{ cal }}
        </div>
        <div class="calendar-buttons">
            <a class="btn btn-info calendar_button_custom" href="{% url 'calendar' %}?{{ prev_month }}">Предыдущий
                месяц</a>
            <a class="btn btn-info calendar_button_custom" href="{% url 'calendar' %}?{{ next_month }}">Следующий
                месяц</a>
        </div>
        <div class="calendar_new_event_button">
            <a class="btn btn-info calendar_button_custom" href="{% url 'event_new' %}">Новое событие</a>
        </div>
        <div class="events-today">
            <h2 class="events_for_today">События на сегодня</h2>
            {% for event in events_today %}
                <a href="{% url 'events_detail' event.pk %}" class="event_card_mini_link">
                    <div class="event_card_mini">
                        <p class="event_name_calendar">
                            {{ event.name }}
                        </p>
                    </div>
                </a>
            {% empty %}
                <p>No events for today.</p>
            {% endfor %}
        </div>
        <div class="calendar-header">
            <h1 class="newsline-header">КАЛЕНДАРЬ МЕРОПРИЯТИЙ</h1>
        </div>
    </div>
{% endblock %}

templates/create_news_ajax.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Newsline{% endblock %}
{% block content %}
<div class="container cont">
    <div class="row d-flex justify-content-center">
        <div class="col-7 card text-bg-light form-margins">
            <h2>Добавление</h2>
   
                <input type="hidden" name="csrfmiddlewaretoken"
                       value="xlrwwWEPHuFakS391qbnZ9xBbiOXIdjOV8CANq3n54bPIwDUI4WRuiPa288O6BQb">

                <div class="mb-3"><label class="form-label" for="id_name">Название</label><input type="text" name="name"
                                                                                                 maxlength="200"
                                                                                                 class="form-control"
                                                                                                 required=""
                                                                                                 id="id_name"></div>
                <div class="mb-3"><label class="form-label" for="id_cities">Город</label><select name="cities"
                                                                                                 class="form-select"
                                                                                                 id="id_cities">
                    <option value="" >---------</option>


                </select></div>
                <div class="mb-3"><label class="form-label" for="id_user">Организатор</label><select name="user"
                                                                                                    class="form-select"
                                                                                                    id="id_user">
                    <option value="" selected="">---------</option>



                </select></div>
                <div class="mb-3"><label class="form-label" for="id_description">Описание</label><textarea
                        name="description" cols="40" rows="10" maxlength="3000" class="form-control" required=""
                        id="id_description"></textarea></div>
                <div class="input-group mb-3">
                    <input type="file" class="form-control" id="id_photo" >
                    <label class="input-group-text" for="inputGroupFile02">Upload</label>
                  </div>
                  
                <button type="submit"  value="Добавить" id="create_id">Создать</button>

        </div>
    </div>
</div>
<script
        src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="{% static 'js/news_create.js' %}"></script>
{% endblock %}

templates/datail_events_ajax.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Newsline{% endblock %}
{% block content %}
<div class="event" id="events"></div>
<button type="submit"  value="" id="update_id">Изменить</button>
<button type="submit"  value="" id="delete">Удалить</button>
<script
        src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="{% static 'js/events_detail.js' %}"></script>
{% endblock %}

templates/datail_news_ajax.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Newsline{% endblock %}
{% block content %}
<div class="event" id="events"></div>
<button type="submit"  value="" id="update_id">Изменить</button>
<button type="submit"  value="" id="delete">Удалить</button>
<script
        src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="{% static 'js/news_detail.js' %}"></script>
{% endblock %}

templates/event.html
{% extends 'base_calendar.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'cal:calendar' %}"> Calendar </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

templates/event_create.html
{% extends 'base_calendar.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left back_to_calendar_link" href="{% url 'calendar' %}"> Calendar </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

templates/events_update.html
{% extends 'base.html' %}
{% block title %}Add Events{% endblock %}
{% block content %}
    <div class="container cont" style="padding-top: 100px;">
        <div class="row d-flex justify-content-center">
            <div class="col-7 card text-bg-light form-margins">
                <h2>Изменение</h2>
                <form method="post" enctype="multipart/form-data">
                    {% include 'partial/create_or_update_events.html' with button='Изменить' %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Welcome!</title>
</head>
<body>
    <h1>Добро пожаловать!</h1>
    <button onclick="location.href='{% url 'login' %}'">Login</button>
    <button onclick="location.href='{% url 'register' %}'">Register</button>
</body>
</html>

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}User Login{% endblock %}
{% block content %}
    <form class="log_form" id="loginForm">
        <h1 class="login_h">АВТОРИЗАЦИЯ</h1>
        <div class="email_log">
            <input class=profile_card_button_login type="email" id="email" required placeholder="Введите почту">
        </div>
        <br>
        <input class=profile_card_button_login type="password" id="password" required placeholder="Введите пароль">
        <br>
        <div class="profile_card_button_wrapper log">
            <span class="profile_card_button">
             <input class=log_btn type="submit" value="Войти">
            </span>
        </div>
    </form>
    <div id="message"></div>
{% endblock %}
{% block script_block %}
    <script src="{% static 'js/login.js' %}"></script>
{% endblock %}

templates/news_create.html
{% extends 'base.html' %}
{% block title %}Create news{% endblock %}
{% block content %}
    <div class="container cont" style="padding-top: 100px;">
        <div class="row d-flex justify-content-center">
            <div class="col-7 card text-bg-light form-margins">
                <h2>Создание новости</h2>
                <form method="post" enctype="multipart/form-data">
                    {% include 'partial/news_form.html' with button_text='Создать' %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/news_update.html
{% extends 'base.html' %}
{% block title %}Update news{% endblock %}
{% block content %}
    <div class="container cont" style="padding-top: 100px;">
        <div class="row d-flex justify-content-center">
            <div class="col-7 card text-bg-light form-margins">
                <h2>Изменение</h2>
                <form method="post" enctype="multipart/form-data">
                    {% include 'partial/news_form.html' with button_text='Изменить' %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/newsline.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Newsline{% endblock %}
{% block content %}
    <div class="about_current_page">
        <h1 class="newsline_header">НОВОСТИ И СОБЫТИЯ</h1>
    </div>
    <div class="events_div">
        <div class="wrapper">
            {% for event in events %}
                <a href="{% url 'events_detail' event.pk %}" class="event_card_link">
                    <div class="event_card">
                        <div class="event_card_image">
                            <img src="{{ event.photo.image.url }}" alt="event_image" class="event_card_img">
                        </div>
                        <div class="event_card_description">
                            <div class="event_card_description_header_div">
                                <h4 class="event_card_description_header">{{ event.name }}</h4>
                            </div>
                            <div class="event_card_description_div">
                                <p class="event_card_description">
                                    {{ event.description|truncatechars_html:130 }}
                                </p>
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}